# Generated by Django 3.2.13 on 2022-05-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(default='jdsfbhdsfds', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
